apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: globby
  annotations:
    version: v0.0.1
    description: "wasmCloud Globby Example"
spec:
  components:
    - name: globby
      type: actor
      properties:
        image: ghcr.io/jordan-rash/globby:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 0.0.0.0:8080
        - type: linkdef
          properties:
            target: blobstore
            values:
              ROOT: "/tmp"

    # Capability Providers
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
    - name: blobstore
      type: capability
      properties:
        image: wasmcloud.azurecr.io/blobstore_fs:0.5.0
        contract: wasmcloud:blobstore
